[project]
name = "leaffliction"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "plotly>=6.5.2",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
]
